import { createSlice } from "@reduxjs/toolkit";

const initialState = [
  {
    first_name: "Helge",
    last_name: "Britland",
    start_date: "21/04/2017",
    department: "Services",
    date_of_birth: "12/15/1994",
    street: "05932 Mallory Way",
    city: "Salt Lake City",
    state: "Utah",
    zip_code: "84170",
  },
  {
    first_name: "Annabela",
    last_name: "Matresse",
    start_date: "26/06/1972",
    department: "Legal",
    date_of_birth: "10/23/2002",
    street: "3 Sachtjen Lane",
    city: "Hartford",
    state: "Connecticut",
    zip_code: "06160",
  },
  {
    first_name: "Corri",
    last_name: "Briton",
    start_date: "26/09/1976",
    department: "Accounting",
    date_of_birth: "10/18/1971",
    street: "2 West Plaza",
    city: "Springfield",
    state: "Illinois",
    zip_code: "62794",
  },
  {
    first_name: "Clayborne",
    last_name: "Conduit",
    start_date: "17/07/2005",
    department: "Product Management",
    date_of_birth: "04/17/1994",
    street: "2 Delaware Center",
    city: "Springfield",
    state: "Massachusetts",
    zip_code: "01152",
  },
  {
    first_name: "Bettine",
    last_name: "Thom",
    start_date: "28/09/2010",
    department: "Research and Development",
    date_of_birth: "05/20/2019",
    street: "46 Pepper Wood Place",
    city: "Flint",
    state: "Michigan",
    zip_code: "48555",
  },
  {
    first_name: "Arnie",
    last_name: "Cockney",
    start_date: "23/05/1996",
    department: "Training",
    date_of_birth: "03/01/2009",
    street: "101 Moulton Circle",
    city: "Melbourne",
    state: "Florida",
    zip_code: "32919",
  },
  {
    first_name: "Lilllie",
    last_name: "MacAndie",
    start_date: "11/03/2020",
    department: "Accounting",
    date_of_birth: "04/15/1989",
    street: "09 Service Crossing",
    city: "Schenectady",
    state: "New York",
    zip_code: "12305",
  },
  {
    first_name: "Louie",
    last_name: "Mosedill",
    start_date: "10/02/1978",
    department: "Services",
    date_of_birth: "08/13/1970",
    street: "28 Ilene Way",
    city: "Tacoma",
    state: "Washington",
    zip_code: "98442",
  },
  {
    first_name: "Roxy",
    last_name: "Ropp",
    start_date: "04/09/2008",
    department: "Product Management",
    date_of_birth: "08/21/2000",
    street: "9235 Cambridge Court",
    city: "Boca Raton",
    state: "Florida",
    zip_code: "33487",
  },
  {
    first_name: "Emilia",
    last_name: "Arpe",
    start_date: "24/09/2003",
    department: "Human Resources",
    date_of_birth: "07/31/2010",
    street: "2 Northland Place",
    city: "Asheville",
    state: "North Carolina",
    zip_code: "28815",
  },
  {
    first_name: "Sax",
    last_name: "Mosley",
    start_date: "28/12/1975",
    department: "Engineering",
    date_of_birth: "09/23/1991",
    street: "0 Northland Way",
    city: "Jeffersonville",
    state: "Indiana",
    zip_code: "47134",
  },
  {
    first_name: "Benjamin",
    last_name: "Curteis",
    start_date: "19/03/1979",
    department: "Human Resources",
    date_of_birth: "01/05/1992",
    street: "066 Katie Road",
    city: "San Diego",
    state: "California",
    zip_code: "92132",
  },
  {
    first_name: "Olvan",
    last_name: "Costa",
    start_date: "09/02/2010",
    department: "Sales",
    date_of_birth: "09/28/2002",
    street: "438 Armistice Trail",
    city: "Columbia",
    state: "South Carolina",
    zip_code: "29240",
  },
  {
    first_name: "Donica",
    last_name: "Lipgens",
    start_date: "10/03/1971",
    department: "Support",
    date_of_birth: "08/14/1993",
    street: "03 Spaight Terrace",
    city: "Portland",
    state: "Oregon",
    zip_code: "97216",
  },
  {
    first_name: "Sal",
    last_name: "Martinovsky",
    start_date: "22/05/2009",
    department: "Legal",
    date_of_birth: "05/15/1971",
    street: "7 American Hill",
    city: "Sandy",
    state: "Utah",
    zip_code: "84093",
  },
  {
    first_name: "Ophelie",
    last_name: "Farndale",
    start_date: "19/04/2016",
    department: "Product Management",
    date_of_birth: "06/17/2001",
    street: "2 Arrowood Point",
    city: "New York City",
    state: "New York",
    zip_code: "10203",
  },
  {
    first_name: "Chiquia",
    last_name: "Adelsberg",
    start_date: "20/01/1972",
    department: "Support",
    date_of_birth: "10/11/1997",
    street: "69779 Coolidge Pass",
    city: "Cleveland",
    state: "Ohio",
    zip_code: "44118",
  },
  {
    first_name: "Valry",
    last_name: "Waters",
    start_date: "14/11/2005",
    department: "Marketing",
    date_of_birth: "10/24/1985",
    street: "60 Dakota Hill",
    city: "Huntsville",
    state: "Alabama",
    zip_code: "35895",
  },
  {
    first_name: "Hall",
    last_name: "Munden",
    start_date: "29/01/2008",
    department: "Training",
    date_of_birth: "02/01/2021",
    street: "20 Nelson Center",
    city: "Tulsa",
    state: "Oklahoma",
    zip_code: "74133",
  },
  {
    first_name: "Base",
    last_name: "Voff",
    start_date: "16/06/1970",
    department: "Accounting",
    date_of_birth: "02/09/2018",
    street: "9 6th Road",
    city: "Boston",
    state: "Massachusetts",
    zip_code: "02283",
  },
  {
    first_name: "Artie",
    last_name: "Harrad",
    start_date: "21/05/2015",
    department: "Services",
    date_of_birth: "09/04/2016",
    street: "21255 Menomonie Center",
    city: "Sacramento",
    state: "California",
    zip_code: "94237",
  },
  {
    first_name: "Chryste",
    last_name: "McMurty",
    start_date: "12/06/2012",
    department: "Legal",
    date_of_birth: "11/03/2005",
    street: "83124 Harbort Street",
    city: "Nashville",
    state: "Tennessee",
    zip_code: "37245",
  },
  {
    first_name: "Barris",
    last_name: "Drivers",
    start_date: "24/12/2011",
    department: "Human Resources",
    date_of_birth: "08/04/1986",
    street: "57 Upham Junction",
    city: "Los Angeles",
    state: "California",
    zip_code: "90020",
  },
  {
    first_name: "Elsi",
    last_name: "Manueau",
    start_date: "14/01/2003",
    department: "Marketing",
    date_of_birth: "03/05/2005",
    street: "7987 Melody Circle",
    city: "Duluth",
    state: "Minnesota",
    zip_code: "55811",
  },
  {
    first_name: "Etta",
    last_name: "Paulsen",
    start_date: "28/06/1970",
    department: "Sales",
    date_of_birth: "07/16/1973",
    street: "49010 Hudson Lane",
    city: "Fairbanks",
    state: "Alaska",
    zip_code: "99790",
  },
  {
    first_name: "Laina",
    last_name: "Bannester",
    start_date: "26/11/2012",
    department: "Product Management",
    date_of_birth: "12/30/1995",
    street: "16 Chinook Parkway",
    city: "Marietta",
    state: "Georgia",
    zip_code: "30061",
  },
  {
    first_name: "Hendrika",
    last_name: "Sutherley",
    start_date: "22/01/1999",
    department: "Training",
    date_of_birth: "12/18/2020",
    street: "93 Fisk Park",
    city: "Washington",
    state: "District of Columbia",
    zip_code: "20005",
  },
  {
    first_name: "Dorine",
    last_name: "Guille",
    start_date: "20/09/1991",
    department: "Research and Development",
    date_of_birth: "02/14/1974",
    street: "115 Bultman Point",
    city: "Bryan",
    state: "Texas",
    zip_code: "77806",
  },
  {
    first_name: "Michaella",
    last_name: "Kondratyuk",
    start_date: "31/10/1993",
    department: "Support",
    date_of_birth: "06/28/1988",
    street: "175 Heffernan Lane",
    city: "Erie",
    state: "Pennsylvania",
    zip_code: "16534",
  },
  {
    first_name: "Jeno",
    last_name: "Halgarth",
    start_date: "24/04/1989",
    department: "Marketing",
    date_of_birth: "04/28/2019",
    street: "172 Bowman Terrace",
    city: "Houston",
    state: "Texas",
    zip_code: "77035",
  },
];

export const employeesSlice = createSlice({
  name: "employeesSlice",
  initialState: initialState,
  reducers: {
    addEmployeeToTheStore: (currentSlice, action) => {
      currentSlice.push(action.payload);
      console.log("addEmployee");
      console.log(action);
    },
  },
});

const { addEmployeeToTheStore } = employeesSlice.actions;
export { addEmployeeToTheStore };
